config/routes.rb
CatarsePaymentWepay::Engine.routes.draw do
  #resources :wepay do
    #collection do
    #  post :ipn
    #end

    #member do
    #  post :refund
    #  get  :review
    #  post :pay
    #  get  :success
    #end
        
  #end

  #resources :merchant, path: "merchant" do
      
  #end
  
  get 'user_setup/:user_id/:proj_id' => 'merchant#user_setup', as: 'wepay_user_setup'
  get 'wepay_oauth_redirect/:user_id/:proj_id' => 'merchant#oauth_account_creation', as: 'wepay_oauth_redirect'
  get 'account_setup/:user_id/:proj_id' => 'merchant#account_setup', as: 'wepay_account_setup'
  get 'account_refresh/:user_id/:proj_id' => 'merchant#account_refresh', as: 'wepay_account_refresh'

  get ':user_id/:proj_id' => "merchant#index", as: 'wepay_account_info'
  get ':user_id' => "merchant#index", as: 'wepay_user_info'
  get '/' => 'merchant#index', as: 'wepay_root'
end

app/models/catarse_payment_wepay/we_pay_account.rb
module CatarsePaymentWepay
  class WePayAccount < ActiveRecord::Base
    attr_accessible :user_id, :proj_id, :account_id, :name, :state, :desc, :owner_user_id, :balances, :statuses
    serialize :balances, JSON
    serialize :statuses, JSON
  end
end

app/models/catarse_payment_wepay/we_pay_token.rb
module CatarsePaymentWepay
  class WePayToken < ActiveRecord::Base
    # TODO: Encrypt WePayToken.access_token
    attr_accessible :user_id, :wepay_user_id, :access_token
  end
end

app/models/catarse_payment_wepay/we_pay_user.rb
module CatarsePaymentWepay
  class WePayUser < ActiveRecord::Base
    attr_accessible :user_id, :wepay_user_id, :first_name, :last_name, :user_name, :email, :state
  end
end

app/controllers/catarse_payment_wepay/application_controller.rb
module CatarsePaymentWepay
  class ApplicationController < ::ApplicationController
    protect_from_forgery :with => :exception
  end
end

app/controllers/catarse_payment_wepay/merchant_controller.rb
require 'catarse_payment_wepay/processors'
require 'wepay'

module CatarsePaymentWepay
  class MerchantController < ApplicationController
    skip_before_filter :force_http

#    before_action :authenticate_user!
    before_filter :factory_wepay_client

    #before_action :authenticate_user!

    def index
      # params contains user_id, project_id from routed url structure
      #puts params
      if params[:user_id] then @user_id = params[:user_id] end
      if params[:proj_id] then @proj_id = params[:proj_id] end
      #puts @user_id
      #puts @proj_id
      
      if @user_id
        @we_pay_user = we_pay_user
        @we_pay_token = we_pay_token
        if @we_pay_token
          @access_token = @we_pay_token[:access_token]
        else
          @access_token = nil
        end
      end
      if @user_id && @proj_id
        @we_pay_account = we_pay_account
      end
      
      case
      when !@user_id
        # if Admin
        # TODO: Display paginated WePayUser/WePayToken list with link to WePayUser/WePayAccount list
        @we_pay_users = CatarsePaymentWepay::WePayUser.paginate(:page => params[:page], :per_page => 25)
        # else !Admin
        # TODO: Display No Access
        #puts 'index'
        render 'user_list'
        
      when @user_id && !@proj_id
        # if current_user.id == User_id
        # TODO: Display User_id
        # TODO: Display WePayToken if exists
        # TODO: Display WePayUser if exists
        # TODO: Display WePayAccount's for User_id
        puts @access_token, @user_id
        if @we_pay_user
          @we_pay_accounts = CatarsePaymentWepay::WePayAccount.where(:user_id => @user_id).paginate(:page => params[:page], :per_page => 10)
          render 'user_token_account_info'
        else
          render 'invalid_user'
        end
        # else
        # TODO: Display No Access
        #puts 'user_token_account_info'
        
      when @user_id && @proj_id && !@access_token
        # if current_user.id == User_id
        # TODO: Display User_id, Project_id
        # TODO: Display user_setup link - wepay_user_setup_path(:user_id => @user_id, :proj_id => @proj_id)
        # else
        # TODO: Display No Access
        #puts 'oauth_authentication'
        render 'oauth_authentication'
                
      when @user_id && @proj_id && @access_token && !@we_pay_account
        # if current_user.id == User_id
        # TODO: Display User_id, Project_id
        # TODO: Display WePayToken
        # TODO: Display WePayUser
        # TODO: Display WePayAccount creation link for @user_id, @proj_id - wepay_project_setup_path(:user_id => @user_id, :project_id => @proj_id)
        # else
        # TODO: Display No Access
        #puts 'account_creation'
        render 'account_creation'

      when @user_id && @proj_id && @access_token && @we_pay_account
        # if current_user.id == User_id
        # TODO: Display WePayToken
        # TODO: Display WePayUser
        # TODO: Display WePayAccount's for @user_id, @proj_id
        # else
        # TODO: Display No Access
        #puts  'account_info'
        render 'account_info'
        
      end
    end
    
    def user_setup
      # params contains user_id, project_id from routed url structure
      # wepay_user_setup_path(:user_id => @user_id, :proj_id => @proj_id)
      #puts params
      @user_id = params[:user_id]
      @proj_id = params[:proj_id]
      
      # redirect url from route helper method
      oauth_redirect_uri = wepay_oauth_redirect_url(:user_id => @user_id, :proj_id => @proj_id)
      #puts oauth_redirect_uri
      oauth_uri =  @wepay.oauth2_authorize_url(oauth_redirect_uri)
      #puts oauth_uri
     
      # Redirect user to WePay OAuth Website
      redirect_to(oauth_uri)
    end
    
    def oauth_account_creation
      # params contains user_id, project_id from routed url structure passed as oauth_redirect_uri in setup
      # params contains either code, or error_code from WePay OAuth Website parameters
      #puts params

      if params[:code] && params[:user_id] && params[:proj_id]
        @oauth_code = params[:code]
        @user_id = params[:user_id]
        @proj_id = params[:proj_id]

        @we_pay_token = we_pay_token
        if @we_pay_token
          @access_token = we_pay_token[:access_token]
        else
          create_wepay_token
        end
        
        if @access_token
          create_wepay_user
        end
        render 'oauth_success'
      else
        # TODO: Edge guard that error_code, error_description were returned   
        @error_code = params[:error_code]
        @error_description = params[:eror_description]
        render 'oauth_failure'
      end
      
    end
    
    def account_setup
      @user_id = params[:user_id]
      @proj_id = params[:proj_id]
      project_name = params[:name]
      project_desc = params[:desc]

      @we_pay_token = we_pay_token
      if @we_pay_token
        @access_token = we_pay_token[:access_token]
      end

      if @access_token
        create_wepay_account project_name, project_desc
        render 'account_creation_success'
      else
        render 'account_creation_failure'
      end
    end
    
    def account_refresh
      @user_id = params[:user_id]
      @proj_id = params[:proj_id]
      if @user_id
        @we_pay_user = we_pay_user
        @we_pay_token = we_pay_token
        if @we_pay_token
          @access_token = @we_pay_token[:access_token]
        else
          @access_token = nil
        end
      end
      if @user_id && @proj_id
        @we_pay_account = we_pay_account
      end
      if @user_id && @proj_id && @we_pay_user && @we_pay_token &&  @access_token  && @we_pay_account
        refresh_wepay_account
        render 'account_info'
      else
        
      end
    end
        
  private
    def factory_wepay_client
      client_id = CatarsePaymentWepay::WePayConfiguration.credentials[:client_id]
      client_secret = CatarsePaymentWepay::WePayConfiguration.credentials[:client_secret]
      use_stage = CatarsePaymentWepay::WePayConfiguration.use_staging
      @wepay = WePay::Client.new(client_id, client_secret, use_stage)
      
      # TODO: Retrive token from storage and inject as instance variable @access_token
    end
    
    def create_wepay_token
      response = @wepay.oauth2_token(@oauth_code, wepay_oauth_redirect_url(:user_id => @user_id, :proj_id => @proj_id))
      puts response
        
      wepay_user_id = response['user_id']
      access_token = response['access_token']
      token_type = response['token_type']

      if access_token
        @access_token = access_token
        # TODO: Store WePay Token - Test for existance first?
        we_pay_token = CatarsePaymentWepay::WePayToken.create(
          :user_id => @user_id,
          :wepay_user_id => wepay_user_id,
          :access_token => access_token)
      else
        # TODO: Edge Guard - Token denial or failure
        we_pay_token = nil
      end
    end

    def create_wepay_user
      response = @wepay.call('/user', @access_token)
      puts response

      wepay_user_id = response['user_id']
      first_name = response['first_name']
      last_name = response['last_name']
      user_name = response['user_name']
      email = response['email']
      state = response['state']
      
      @we_pay_user = CatarsePaymentWepay::WePayUser.create(
        :user_id => @user_id,
        :wepay_user_id => wepay_user_id,
        :first_name => first_name,
        :last_name => last_name,
        :user_name => user_name,
        :email => email,
        :state => state)        
    end

    def create_wepay_account(project_name, project_desc)
      response = @wepay.call('/account/create', @access_token, {
        :name        => project_name,
        :description => project_desc
      })
      puts response
      account_id = response['account_id']
      name = response['name']
      state = response['state']
      desc = response['description']
      owner_user_id = response['owner_user_id']
      balances = response['balances']
      statuses = response['statuses']
      
      @we_pay_account = CatarsePaymentWepay::WePayAccount.create(
        :account_id => account_id,
        :name => name,
        :state => state,
        :desc => desc,
        :owner_user_id => owner_user_id,
        :balances => balances,
        :statuses => statuses,
        :user_id => @user_id,
        :proj_id => @proj_id
      )
    end
    
    def refresh_wepay_account
      response = @wepay.call('/account', @access_token, {
        :account_id => @we_pay_account.account_id
      })
      puts response
      
      account_id = response['account_id']
      name = response['name']
      state = response['state']
      desc = response['description']
      owner_user_id = response['owner_user_id']
      balances = response['balances']
      statuses = response['statuses']
      
      # Found the account for the project
      # The project found account matches the account_id from WePay
      # The project found owner_user_id matches thw owner_user_id from WePay - would break WePayUser RI
      # Same account_id and owner_user_id
      if @we_pay_account && (@we_pay_account.account_id.to_i == account_id) && (@we_pay_account.owner_user_id == owner_user_id.to_s) then
        @we_pay_account.name = name
        @we_pay_account.state = state
        @we_pay_account.desc = desc
        @we_pay_account.balances = balances
        @we_pay_account.statuses = statuses        
        @we_pay_account.save
      else
        # TODO: Error from WePay -or- Key field issues -or- WePay Owner change 
      end
    end
    
    def we_pay_token
      we_pay_tokens = CatarsePaymentWepay::WePayToken.find_by_user_id @user_id.to_i
    end
    
    def we_pay_user
      we_pay_user = CatarsePaymentWepay::WePayUser.find_by_user_id @user_id.to_i
    end
     
    def we_pay_account

app/controllers/catarse_payment_wepay/wepay_controller.rb
require 'catarse_payment_wepay/processors'

module CatarsePaymentWepay::Payment
  class WepayController < ApplicationController
    skip_before_filter :verify_authenticity_token, :only => [:notifications]
    skip_before_filter :detect_locale, :only => [:notifications]
    skip_before_filter :set_locale, :only => [:notifications]
    skip_before_filter :force_http

    before_filter :setup_gateway

    SCOPE = "projects.backers.wepay"

    layout :false

    def review

    end

  end
end

app/helpers/catarse_payment_wepay/application_helper.rb
module CatarsePaymentWepay
  module ApplicationHelper
  end
end

app/views/catarse_payment_wepay/merchant/account_creation.html.slim
#account-creation
  <h2>WePay Account Creation</h2>
  =link_to 'Project Account Creation', wepay_account_setup_path(:user_id => @user_id, :proj_id => @proj_id, :params => {:name => "Project Name", :desc => "Project description"}) 

app/views/catarse_payment_wepay/merchant/account_creation_failure.html.slim
#wepay-account-creation-success
  <h2>WePay Project Account Creation Failure</h2>

app/views/catarse_payment_wepay/merchant/account_creation_success.html.slim
#wepay-account-creation-success
  <h2>WePay Project Account Creation Success</h2>
  =link_to 'Return to WePay Account Info',  wepay_account_info_path(:user_id => @user_id, :proj_id => @proj_id)

app/views/catarse_payment_wepay/merchant/account_info.html.slim
#account-info
  <h2>WePay Account Info</h2>
  <h3>User Name</h3>
  #wepay-user-info
  	=@we_pay_user.user_name
  <h3>Account Name</h3>
  #wepay-account-name
  	=@we_pay_account.name
  <h3>Account Desc</h3>
  #wepay-account-desc
  	=@we_pay_account.desc
  <h3>Account Id</h3>
  #wepay-account-info
  	=@we_pay_account.account_id
  <h3>Account State</h3>
  #wepay-account-state
  	=@we_pay_account.state
  <h3>Account Owner User Id</h3>
  #wepay-user-owner-id
  	=@we_pay_account.owner_user_id
  <h3>Account Status</h3>
  #wepay-account-status
  	=@we_pay_account.statuses
  <h3>Account Balances</h3> 
  #wepay-account-balance
  	=@we_pay_account.balances
  #wepay-account-refresh
  	=link_to 'Refresh WePay Account Info',  wepay_account_refresh_path(:user_id => @user_id, :proj_id => @proj_id)
  #wepay-return-nav
  	=link_to 'Return to WePay User Info',  wepay_user_info_path(:user_id => @user_id)

app/views/catarse_payment_wepay/merchant/invalid_user.html.slim
=javascript_include_tag 'catarse_payment_wepay'
#user-token-account-info
  <h2>WePay User does NOT exist</h2>
  =link_to 'Return to WePay Users List', wepay_root_path

app/views/catarse_payment_wepay/merchant/oauth_authentication.html.slim
#wepay-oauth
  <h2>WePay OAuth Authentication</h2>
  =link_to 'Authentication with WePay', wepay_user_setup_path(:user_id => @user_id, :proj_id => @proj_id)

app/views/catarse_payment_wepay/merchant/oauth_failure.html.slim
=javascript_include_tag 'catarse_payment_wepay'
#wepay-oauth-failure
  <h2>WePay OAuth Failure</h2>
  =link_to 'Return to WePay User Info',  wepay_user_info_path(:user_id => @user_id)

app/views/catarse_payment_wepay/merchant/oauth_success.html.slim
=javascript_include_tag 'catarse_payment_wepay'
#wepay-oauth-success
  <h2>WePay OAuth Success</h2>
  =link_to 'Return to WePay User Info',  wepay_user_info_path(:user_id => @user_id)

app/views/catarse_payment_wepay/merchant/user_list.html.erb
<% javascript_include_tag 'catarse_payment_wepay' %>
<div id='catarse_payment_wepay_user_list'>
<h2>WePay Merchant Collection - Paginated List of WePayUsers</h2>
</div>
<%= will_paginate(@we_pay_users, previous_label: h("<"), next_label: h(">")) %>
<table>
<% for we_pay_user in @we_pay_users %>
	<tr>
	<td>
	<%= link_to( we_pay_user.user_name,  wepay_user_info_path(:user_id => we_pay_user.user_id)) %>
	</td>
	<td>
	<%= we_pay_user.last_name + ', ' + we_pay_user.first_name %>
	</td>
	<td>
	<%= we_pay_user.email %>
	</td>
	<td>
	<%= we_pay_user.wepay_user_id%>
	</td>
	</tr>
<% end %>
</table>

app/views/catarse_payment_wepay/merchant/user_token_account_info.html.slim
=javascript_include_tag 'catarse_payment_wepay'
#user-token-account-info
  <h2>WePayUser, WePayToken, and WePayAccounts Info</h2>
  =link_to 'Return to WePay Users List', wepay_root_path
  <div>
    =@we_pay_user.last_name + ', ' + @we_pay_user.first_name
  </div>
  <div>
    =@we_pay_token.access_token
  </div>
  =will_paginate(@we_pay_accounts, previous_label: h("<"), next_label: h(">"))
  <table>
  - for we_pay_account in @we_pay_accounts
    <tr>
    <td>
      =we_pay_account.name
    </td>
    <td>
      =we_pay_account.desc
    </td>
    <td>
      =link_to we_pay_account.account_id, wepay_account_info_path(:user_id => @user_id, :proj_id => we_pay_account.proj_id)
    </td>
    </tr>
  </table>